<?php

// ----------------------------------------------------------
// Module exportation dfsi
// Amael Hervoche
// 21/01/2014
// ----------------------------------------------------------


module_load_include( _DFSI_INCLUDE_EXTENSION , "dfsiexport" , "dfsiexport.define");
module_load_include( _DFSI_INCLUDE_EXTENSION , "dfsi" , "dfsi.define");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.permissions");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.menu");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.form");
module_load_include( _DFSI_INCLUDE_EXTENSION , _DFSIEXPORT_MODULE_NAME , "dfsiexport.api");




